Cache proxy implementation
C4T-BuT-S4D/S4DFarm pull request #10
Opened 2022-07-15 16:38 UTC by jnovikov

This PR will add new microservice for caching http responses in Redis that might be used to retrieve attack-data on laggy CTFs. 

See the example of usage:
https://gist.github.com/jnovikov/c355433e1173ca72d1576727f6851960

2022-07-15 18:29 UTC, pomo-mondreganto requested changes
Хочу флажок для рефреша кеша

2022-07-15 21:25 UTC, jnovikov commented on httpproxy/proxy/main.go
> +		cachedResp, err := http.ReadResponse(bufio.NewReader(strings.NewReader(cachedResponseString)), r)
Почему ? bytes.Buffer mutable, strings.Reader - нет, тем более у меня уже строка из редиса приходит

2022-07-15 21:25 UTC, jnovikov commented on httpproxy/proxy/main.go
> +const PORT = "8888"
Убрал

2022-07-15 21:26 UTC, jnovikov commented on httpproxy/proxy/main.go
> +	return 0
В редис не попадает 0 в таймаут. Если таймаут 0 - кэширования не будет (проверка в OnResponse)

2022-07-16 06:26 UTC, pomo-mondreganto approved these changes

2022-07-16 06:27 UTC, merged